name: Semgrep Security Scan

on:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto --severity ERROR .





