name: Run Semgrep

on:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config=auto --severity ERROR --error \
            --exclude=.github/workflows/ci.yml \
            --exclude=.github/workflows/update-challenges-www-legacy.yml \
            --exclude=.github/workflows/update-challenges-ebook.yml \
            --exclude=data/static/codefixes/ \
            --exclude=data/static/users.yml \
            --exclude=frontend/src/app/app.guard.spec.ts \
            .
